### ISSUE TITLE
Translate placeholder on input not working

### ISSUE THREAD

**Issue by samal84** [MichaReiser/webpack-angular-translate#20]
I don't know if anyone else is getting this issue, but when I try to use placehold on an input I get the translation key written as the placeholder and not the default translation string.

```
<input
  type="text"
  translate
  translate-attr-placeholder="i see this translattion key"
  translate-default-attr-placeholder="when i expect to see this default translation string">
```

**Comment by samal84** [comment]
On further investigation I've found that the translation extraction works fine. The key and value are both stored properly in the output translation file. We may have something borked in our webpack or angular setup.

**Comment by MichaReiser** [comment]
... funny.. I just wanted to ask to give me a complete example since your example passes in a unit test. But in this case, everything is fine. Thanks for closing the issue.

I hope you can locate the source of your problems soon.
