### ISSUE TITLE
webpack2 question

### ISSUE THREAD

**Issue by BenDiuguid** [MichaReiser/webpack-angular-translate#21]
I saw that there is a webpack2 branch, and I would love a release that works with webpack2 if possible! 😄

**Comment by MichaReiser** [comment]
This branch is quite old... I don't even remember to have created it ;) As you, I also would like to see a webpack 2 version of this project (and I'm glad, you are using it).

Are you facing any specific issues or is it just the semver that needs to be updated?

As I'm currently studying for my oncoming exams I do not have time to do the upgrade in the next three weeks. Maybe after that, but I have just one week of. 

So I want to encourage you to create a fork and just try to upgrade the semver. If all unit tests are still running after that, then I can merge your pull request promptly and release a new version.

**Comment by BenDiuguid** [comment]
So to be more specific, I'm trying to enable tree-shaking in webpack2, and this needs a `.babelrc` like so:

```
{
  "presets": [
    ["es2015", { "modules": false}]
  ]
}
```

This disables babel from transpliling you're modules, and allows webpack2 to bundle them.

When using WebpackAngularTranslate, I get the following error:

```
ERROR in ./app/app.module.js
Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Parser.pp.raise (/Users/benjamind/projects/ultipro-mobile-app/node_modules/acorn/dist/acorn.js:918:13)
    at Parser.pp.parseStatement (/Users/benjamind/projects/ultipro-mobile-app/node_modules/acorn/dist/acorn.js:1739:34)
    at Parser.pp.parseTopLevel (/Users/benjamind/projects/ultipro-mobile-app/node_modules/acorn/dist/acorn.js:1645:21)
    at Parser.parse (/Users/benjamind/projects/ultipro-mobile-app/node_modules/acorn/dist/acorn.js:1613:17)
    at Object.parse (/Users/benjamind/projects/ultipro-mobile-app/node_modules/acorn/dist/acorn.js:880:44)
    at extractTranslations (/Users/benjamind/projects/ultipro-mobile-app/node_modules/webpack-angular-translate/src/js/js-loader.ts:38:34)
    at Object.jsLoader (/Users/benjamind/projects/ultipro-mobile-app/node_modules/webpack-angular-translate/src/js/js-loader.ts:31:5)
 @ multi webpack-dev-server/client?http://localhost:3000/ ./app/app.module.js
```

Which seems like WebpackAngularTranslate is trying to do something with the modules?

Maybe I'm using the library wrong, but here is the slice of my webpack.config that matters 😄 

```javascript
module: {
      rules: [
        {
          // The webpack-angular-translate html loader must be run as a preloader as it expects the HTML as input prior to it being bundled into js
          enforce: 'pre',
          test: /\.html$/,
          exclude: /(plugins|styles|teamcity|templates|hooks)/,
          loader: WebPackAngularTranslate.htmlLoader(),
        },
        {
          test: /\.js$/,
          exclude: /(plugins|styles|teamcity|templates|hooks)/,
          use: [
            WebPackAngularTranslate.jsLoader(),
            'babel-loader',
          ],
        },
       // ...
]}

```

**Comment by MichaReiser** [comment]
hmm yeah... So the actual problem is the outdated version of acorn that is not capable parsing the javascript files (does not support ES6 syntax). 

As long as you are not using the translate service in your code, you can just exclude the angular-translate js loader.

But overall, upgrading all dependencies to the latest versions is definitely something I have to do sometime soon... If I just have the time to so.

**Comment by BenDiuguid** [comment]
I can submit a PR for updating the dependencies if you think that is the only issue?

**Comment by MichaReiser** [comment]
I think just updating the dependencies is not enough. If you look at the [acorn documentation](https://github.com/ternjs/acorn#main-parser), then you can see that there is an options flag  `sourceType` that needs to be set.

So I think we have the update the dependency and as well provide an option to pass acorn-options to the jsloader that are used on [line 38](https://github.com/MichaReiser/webpack-angular-translate/blob/master/src/js/js-loader.ts#L38).  This way the source type can be configured...

**Comment by BenDiuguid** [comment]
I have submitted a PR (#22) and you we're right, I simply had to update the dependencies and add a few acorn options.
