### ISSUE TITLE
Cannot download 1.0.0

### ISSUE THREAD

**Issue by BenDiuguid** [MichaReiser/webpack-angular-translate#26]
I was just curious if anyone was experiencing this issue. I cannot download with `yarn` or `npm` the latest version (1.0.0) of `webpack-angular-translate`. Might be an npm registry issue, not sure, I was just curious if anyone is experiencing the same error?

**error**: `https://registry.yarnpkg.com/webpack-angular-translate/-/webpack-angular-translate-1.0.0.tgz: invalid tar file`

**Comment by MichaReiser** [comment]
I released a new version... I hope this fixes the issue... No idea what went wrong. Sorry for the inconvenience.

**Comment by BenDiuguid** [comment]
That worked! I have no idea why it was failing. I've never seen an issue like that before. Thanks for being speedy!!

**Comment by MichaReiser** [comment]
Glad to here that... Hope there are no other issues. Seems like I got out of practice... Maybe it's time to automate the releasing

**Comment by MichaReiser** [comment]
Strange... seems like publishing using yarn does not work??? I Will try again using npm

**Comment by MichaReiser** [comment]
Can you try again?

**Comment by BenDiuguid** [comment]
Yes, it worked this time! Thanks!
