### ISSUE TITLE
Enable extraction of translation for hybrid applications

### ISSUE THREAD

**Issue by jebner** [MichaReiser/webpack-angular-translate#37]
We run an application in hybrid mode (mixed angularJS and angular application using ng-upgrade), 
whose angularJS part uses `angular-translate` for i18n and relies on `webpack-angular-translate` for translation extraction.
Now, going forward, we would like to use the  angular `i18n` and `i18n-[attr]` directives for i18n in all new code. 
Due to the hybrid setup, we can not use the regular angular-cli tooling, webpack plugin or standalone x-i18n tool for translation extraction. 
Instead we would like to stick with `webpack-angular-translate` and have it extract all translations from the templates of the new code 
together with the existing ones from angularJS templates. This would allow us to extract all translations in one go with a single webpack plugin.

Would it be possible to extend `webpack-angular-translate` for these directives?

Desired behaviour:

`<h1 i18n="@@A title">A title</h1>` should extract a translation with 
id and default translation "A title". (With the `@@` prefix angular allows to set custom ids).

`<p i18n="@@loan-intro-description-text">This is a very long text for the loan intro!</p>` 
should extract a translation with id `loan-intro-description-text` and default translation "This is a very long text for the loan intro!".

`<img src=... title="My image title" i18n-title="@@MyImage" />` should extract a translation with
id `MyImage` and default translation `My image title`.

Angular allows to add a description and a meaning to a `i18n` attribute like this: `i18n-x="<meaning>|<description>@@<id>"`.
In this case it's okay to just drop / ignore the meaning and the description and only extract the id. 

Note: The extraction will only work for labels with an explicitly provided `@@id` (otherwise `webpack-angular-translate` would have to emulate the angular translation id generation algorithm). 
We would suggest to even throw an error in case a translation is encountered that should be extracted but does not have an explicit id.

Let us know if we can help by providing a PR. Thank you.

**Comment by sambernet** [comment]
Note that this is somewhat related to #36, as a solution to #36 that uses callbacks could probably be reused to implement this use-case as well. 

For this to work we would also need to be able to use a regex to match the tag-names, as the `i18n` and `i18n-xy` attributes can be placed on arbitrary tags - providing an exhaustive list is thus not reasonable.

**Comment by MichaReiser** [comment]
Hi @jebner and @sambernet 

Thanks for bringing up this issue and this well-written description. 
I started a PR #38 that hopefully exposes the API needed to implement your desired feature. Can you take a look at the PR to verify if this is the case? Furthermore, it would help me if you can help me to clarify the open issues I mentioned in the PR since I myself are no longer familiar with angular.

You mentioned that you are willing to contribute. It would be amazing to see a PR that adds the mentioned functionality with documentation added to the README how to use it :)

**Comment by MichaReiser** [comment]
Released with version 3.2.0
